<?php
/**
 * GetCardPaymentMethodResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwenta API
 *
 * Kwenta OpenAPI documentation
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetCardPaymentMethodResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetCardPaymentMethodResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetCardPaymentMethodResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'brand' => 'string',
        'last4' => 'string',
        'expMonth' => 'int',
        'expYear' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'brand' => null,
        'last4' => null,
        'expMonth' => null,
        'expYear' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'brand' => false,
		'last4' => false,
		'expMonth' => false,
		'expYear' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'brand' => 'brand',
        'last4' => 'last4',
        'expMonth' => 'expMonth',
        'expYear' => 'expYear'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'brand' => 'setBrand',
        'last4' => 'setLast4',
        'expMonth' => 'setExpMonth',
        'expYear' => 'setExpYear'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'brand' => 'getBrand',
        'last4' => 'getLast4',
        'expMonth' => 'getExpMonth',
        'expYear' => 'getExpYear'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('last4', $data ?? [], null);
        $this->setIfExists('expMonth', $data ?? [], null);
        $this->setIfExists('expYear', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['brand']) && (mb_strlen($this->container['brand']) > 100)) {
            $invalidProperties[] = "invalid value for 'brand', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['brand']) && (mb_strlen($this->container['brand']) < 1)) {
            $invalidProperties[] = "invalid value for 'brand', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['last4']) && (mb_strlen($this->container['last4']) > 4)) {
            $invalidProperties[] = "invalid value for 'last4', the character length must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['last4']) && (mb_strlen($this->container['last4']) < 4)) {
            $invalidProperties[] = "invalid value for 'last4', the character length must be bigger than or equal to 4.";
        }

        if (!is_null($this->container['expMonth']) && ($this->container['expMonth'] > 12)) {
            $invalidProperties[] = "invalid value for 'expMonth', must be smaller than or equal to 12.";
        }

        if (!is_null($this->container['expMonth']) && ($this->container['expMonth'] < 1)) {
            $invalidProperties[] = "invalid value for 'expMonth', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['expYear']) && ($this->container['expYear'] > 2123)) {
            $invalidProperties[] = "invalid value for 'expYear', must be smaller than or equal to 2123.";
        }

        if (!is_null($this->container['expYear']) && ($this->container['expYear'] < 2023)) {
            $invalidProperties[] = "invalid value for 'expYear', must be bigger than or equal to 2023.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets brand
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string|null $brand Brand of the card
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        if ((mb_strlen($brand) > 100)) {
            throw new \InvalidArgumentException('invalid length for $brand when calling GetCardPaymentMethodResponse., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($brand) < 1)) {
            throw new \InvalidArgumentException('invalid length for $brand when calling GetCardPaymentMethodResponse., must be bigger than or equal to 1.');
        }

        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets last4
     *
     * @return string|null
     */
    public function getLast4()
    {
        return $this->container['last4'];
    }

    /**
     * Sets last4
     *
     * @param string|null $last4 last 4 digit of the card number
     *
     * @return self
     */
    public function setLast4($last4)
    {
        if (is_null($last4)) {
            throw new \InvalidArgumentException('non-nullable last4 cannot be null');
        }
        if ((mb_strlen($last4) > 4)) {
            throw new \InvalidArgumentException('invalid length for $last4 when calling GetCardPaymentMethodResponse., must be smaller than or equal to 4.');
        }
        if ((mb_strlen($last4) < 4)) {
            throw new \InvalidArgumentException('invalid length for $last4 when calling GetCardPaymentMethodResponse., must be bigger than or equal to 4.');
        }

        $this->container['last4'] = $last4;

        return $this;
    }

    /**
     * Gets expMonth
     *
     * @return int|null
     */
    public function getExpMonth()
    {
        return $this->container['expMonth'];
    }

    /**
     * Sets expMonth
     *
     * @param int|null $expMonth Expiration month of the card
     *
     * @return self
     */
    public function setExpMonth($expMonth)
    {
        if (is_null($expMonth)) {
            throw new \InvalidArgumentException('non-nullable expMonth cannot be null');
        }

        if (($expMonth > 12)) {
            throw new \InvalidArgumentException('invalid value for $expMonth when calling GetCardPaymentMethodResponse., must be smaller than or equal to 12.');
        }
        if (($expMonth < 1)) {
            throw new \InvalidArgumentException('invalid value for $expMonth when calling GetCardPaymentMethodResponse., must be bigger than or equal to 1.');
        }

        $this->container['expMonth'] = $expMonth;

        return $this;
    }

    /**
     * Gets expYear
     *
     * @return int|null
     */
    public function getExpYear()
    {
        return $this->container['expYear'];
    }

    /**
     * Sets expYear
     *
     * @param int|null $expYear Expiration year of the card
     *
     * @return self
     */
    public function setExpYear($expYear)
    {
        if (is_null($expYear)) {
            throw new \InvalidArgumentException('non-nullable expYear cannot be null');
        }

        if (($expYear > 2123)) {
            throw new \InvalidArgumentException('invalid value for $expYear when calling GetCardPaymentMethodResponse., must be smaller than or equal to 2123.');
        }
        if (($expYear < 2023)) {
            throw new \InvalidArgumentException('invalid value for $expYear when calling GetCardPaymentMethodResponse., must be bigger than or equal to 2023.');
        }

        $this->container['expYear'] = $expYear;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


